/** @type {import('tailwindcss').Config} */
module.exports = {
  important: true,
  darkMode: false,
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './demo/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '1rem',
    },
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--warning-foreground)',
        },
        danger: {
          DEFAULT: 'var(--danger)',
          foreground: 'var(--danger-foreground)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--success-foreground)',
        },
        /* ── DISHA 4.0 HCOS™ PRIMARY SCALE ── */
        primary: {
          800: '#11658C',
          600: '#1581B2',
          500: '#1A9DD9',
          200: '#B9E1F4',
          100: '#DCEFF7',
          DEFAULT: '#1A9DD9',
          hover: '#1581B2',
          dark: '#11658C',
          light: '#DCEFF7',
          foreground: '#FFFFFF',
        },
        secondary: {
          DEFAULT: '#0D9488',
          hover: '#0F766E',
          light: '#CCFBF1',
          foreground: '#FFFFFF',
        },
        /* ── DISHA 4.0 HCOS™ GRAY NEUTRAL SCALE ── */
        gray: {
          black: '#0B1A2F',
          90: '#233144',
          80: '#3C4859',
          70: '#546173',
          50: '#909BB1',
          20: '#CCD3E3',
          10: '#E4E8F0',
          3: '#F9FAFB',
          white: '#FFFFFF',
          DEFAULT: '#546173',
          dark: '#0B1A2F',
          light: '#F9FAFB',
        },
        /* ── DISHA 4.0 HCOS™ ERROR STATE PALETTE ── */
        error: {
          dark: '#9A0266',
          main: '#B7007B',
          vibrant: '#E66EA8',
          accent: '#DC7BA8',
          mid: '#D8B9C8',
          soft: '#E8CFDC',
          light: '#FAD9E9',
          DEFAULT: '#B7007B',
          hover: '#9A0266',
        },
        /* ── Helm palette → canonical DISHA tokens ── */
        'watch-green': '#FFFFFF',
        'watch-green-dark': '#F9FAFB',
        'watch-green-light': '#E4E8F0',
        'brass-gold': '#1581B2',
        'brass-gold-light': '#1A9DD9',
        'brass-gold-dark': '#11658C',
        'chart-cream': '#3C4859',
        'near-black': '#0B1A2F',
        /* ── DISHA 4.0 HCOS Design System surfaces ── */
        disha: {
          bg: '#F9FAFB',
          surface: '#FFFFFF',
          border: '#CCD3E3',
          borderGlow: '#909BB1',
          accent: {
            emerald: '#1581B2',
            violet: '#11658C',
            cyan: '#1A9DD9',
            amber: '#D97706',
            rose: '#B7007B',
          },
        },
        /* ── Fusonic ERP Design System Tokens (CSS var-backed) ── */
        erp: {
          navy: 'var(--erp-navy)',
          slate: 'var(--erp-slate)',
          bg: 'var(--erp-bg)',
          surface: 'var(--erp-surface)',
          border: 'var(--erp-border)',
          textMain: 'var(--erp-text-main)',
          textMuted: 'var(--erp-text-muted)',
          accent: 'var(--erp-accent)',
          accentHover: 'var(--erp-accent-hover)',
          indigo: 'var(--erp-indigo)',
          success: 'var(--erp-success)',
          warning: 'var(--erp-warning)',
          danger: 'var(--erp-danger)',
        },
        /* ── Fusonic "Farben" Exact Palette — mapped to DISHA 4.0 tokens ── */
        fusonic: {
          /* Primary Blues — canonical DISHA 4.0 values */
          p800: '#11658C',
          p600: '#1581B2',
          p500: '#1A9DD9',
          p200: '#B9E1F4',
          p100: '#DCEFF7',
          /* Grays — canonical DISHA 4.0 values */
          black: '#0B1A2F',
          g90: '#233144',
          g80: '#3C4859',
          g70: '#546173',
          g50: '#909BB1',
          g20: '#CCD3E3',
          g10: '#E4E8F0',
          g3:  '#F9FAFB',
          white: '#FFFFFF',
          /* Errors — canonical DISHA 4.0 error tokens */
          errDark: '#9A0266',
          errMain: '#B7007B',
          errMid:  '#E66EA8',
          errLight:'#FAD9E9',
          /* Fusonic Farben LIGHT Design System Tokens */
          'light-canvas': '#F9FAFB',
          'light-canvas-alt': '#E4E8F0',
          'light-surface': 'rgba(255,255,255,0.80)',
          'light-surface-elevated': '#FFFFFF',
          'light-border': '#CCD3E3',
          'light-border-strong': '#909BB1',
          'light-text-primary': '#233144',
          'light-text-body': '#3C4859',
          'light-text-muted': '#546173',
          'light-brand': '#1A9DD9',
          'light-brand-mid': '#1581B2',
          'light-brand-end': '#11658C',
          'light-cyan': '#1A9DD9',
          'light-violet': '#11658C',
          'light-emerald': '#0D9488',
          'light-amber': '#D97706',
          /* ── FUSONIC FARBEN LIGHT CANONICAL TOKENS ── */
          canvas: '#F9FAFB',
          'surface-card': '#FFFFFF',
          'surface-border': '#CCD3E3',
          'text-primary': '#233144',
          'text-subtle': '#546173',
          'badge-bg': '#DCEFF7',
          'badge-text': '#11658C',
          'focus-ring': '#B9E1F4',
          'primary-DEFAULT': '#1A9DD9',
          'primary-hover': '#1581B2',
          'primary-light': '#DCEFF7',
          'secondary-DEFAULT': '#0D9488',
          'secondary-hover': '#0F766E',
          'secondary-light': '#CCFBF1',
          /* ── FUSONIC FARBEN LIGHT SYSTEM (Strict Palette) ── */
          bg: '#FFFFFF',
          surface: '#F8FAFC',
          elevated: '#F1F5F9',
          brand: '#1A9DD9',
          brandHover: '#1581B2',
          tint: '#EFF6FF',
          heading: '#0F172A',
          body: '#475569',
          muted: '#64748B',
          border: '#E2E8F0',
          success: '#16A34A',
          /* Dark tokens preserved for compatibility */
          panel: '#3C4859',
          primary: '#1A9DD9',
          secondary: '#0D9488',
          accent: '#1581B2',
        },
        /* ── CANONICAL FUSONIC FARBEN TOKEN MAP (farben namespace) ── */
        farben: {
          // Primary Blues
          'primary-800': '#11658C',
          'primary-600': '#1581B2',
          'primary-500': '#1A9DD9',
          'primary-200': '#B9E1F4',
          'primary-100': '#DCEFF7',
          // Neutral Grays
          'black': '#0B1A2F',
          'gray-90': '#233144',
          'gray-80': '#3C4859',
          'gray-70': '#546173',
          'gray-50': '#909BB1',
          'gray-20': '#CCD3E3',
          'gray-10': '#E4E8F0',
          'gray-3': '#F9FAFB',
          'white': '#FFFFFF',
        },
      },
      backgroundColor: {
        'app-canvas': '#F9FAFB',
        'surface-card': '#FFFFFF',
      },
      borderColor: {
        'app-border': '#CCD3E3',
        'primary-focus': '#B9E1F4',
        'error-border': '#E66EA8',
        'error-subtle': '#E8CFDC',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        sm: '2px',
        md: '4px',
        lg: '6px',
        xl: '8px',
        '2xl': '12px',
      },
      fontFamily: {
        sans: ['"Public Sans"', 'Inter', 'DM Sans', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Cal Sans', 'Manrope', 'Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Fira Code', 'IBM Plex Mono', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
      },
      backgroundImage: {
        'grid-schematic': "linear-gradient(rgba(26,157,217,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(26,157,217,0.04) 1px, transparent 1px)",
        'radial-glow': 'radial-gradient(circle at 50% 0%, rgba(17, 101, 140, 0.12) 0%, transparent 70%)',
        'glass-gradient': 'linear-gradient(180deg, rgba(255, 255, 255, 0.05) 0%, rgba(255, 255, 255, 0.01) 100%)',
        'neon-border': 'linear-gradient(90deg, #1581B2, #11658C, #1A9DD9)',
        'mesh-dark': "radial-gradient(at 40% 20%, rgba(26,157,217,0.08) 0px, transparent 50%), radial-gradient(at 80% 0%, rgba(17,101,140,0.06) 0px, transparent 50%), radial-gradient(at 0% 50%, rgba(26,157,217,0.05) 0px, transparent 50%)",
        'fusonic-gradient': 'linear-gradient(135deg, #1A9DD9 0%, #0D9488 100%)',
        'fusonic-glow': 'radial-gradient(circle, rgba(26,157,217,0.10) 0%, rgba(249,250,251,0) 70%)',
      },
      backgroundSize: {
        'grid': '48px 48px',
      },
      boxShadow: {
        'glow-emerald': '0 0 20px -5px rgba(13, 148, 136, 0.3)',
        'glow-violet': '0 0 20px -5px rgba(17, 101, 140, 0.3)',
        'glow-cyan': '0 0 20px -5px rgba(26, 157, 217, 0.3)',
        'glow-amber': '0 0 20px -5px rgba(217, 119, 6, 0.3)',
        'glow-rose': '0 0 20px -5px rgba(183, 0, 123, 0.3)',
        'glass-card': '0 8px 32px 0 rgba(11, 26, 47, 0.08)',
        'glass-card-hover': '0 16px 48px 0 rgba(11, 26, 47, 0.12)',
        'erp-card': '0 1px 3px 0 rgba(11, 26, 47, 0.05), 0 1px 2px -1px rgba(11, 26, 47, 0.05)',
        'erp-popover': '0 10px 15px -3px rgba(11, 26, 47, 0.08), 0 4px 6px -4px rgba(11, 26, 47, 0.04)',
        'fusonic-sm': '0 1px 2px 0 rgba(11, 26, 47, 0.05)',
        'fusonic-md': '0 4px 6px -1px rgba(11, 26, 47, 0.08), 0 2px 4px -2px rgba(11, 26, 47, 0.04)',
        'fusonic-lg': '0 10px 15px -3px rgba(11, 26, 47, 0.1), 0 4px 6px -4px rgba(11, 26, 47, 0.05)',
      },
      animation: {
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s infinite linear',
        'float': 'float 6s ease-in-out infinite',
        'neon-pulse': 'neonPulse 2s ease-in-out infinite',
        'grid-flow': 'gridFlow 8s linear infinite',
        'scan-line': 'scanLine 12s linear infinite',
        'pulse-dot': 'pulseDot 2s ease-in-out infinite',
        'fade-in': 'fadeIn 0.3s ease-out forwards',
      },
    },
  },
  plugins: [],
};